# Generated by Django 2.1b1 on 2019-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
                ('attributes', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
                ('anotherclass', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
                ('methods', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
                ('nextclass', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifiedAggrigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NotIdentifiedClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seq_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(max_length=500)),
                ('reciever', models.TextField(max_length=500)),
                ('Message', models.TextField(max_length=500)),
                ('loop', models.TextField(max_length=500)),
                ('MessageType', models.TextField(max_length=500)),
                ('conditions', models.TextField(max_length=500)),
                ('conditionMsg', models.TextField(max_length=500)),
                ('elsemsg', models.TextField(max_length=500)),
                ('sender_else', models.TextField(max_length=500)),
                ('reciver_else', models.TextField(max_length=500)),
                ('conditionBit', models.TextField(max_length=500)),
                ('If_loop', models.TextField(max_length=500)),
                ('else_loop', models.TextField(max_length=500)),
                ('SeqId', models.TextField(max_length=500)),
            ],
        ),
    ]
